background {
    monitor =
    path = /home/withold/.config/hypr/wallpapers/artemis-wide.jpg
    blur_passes = 0
    blur_size = 4
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(33ccff)
    inner_color = rgb(1a1a2e)
    font_color = rgb(ffffff)
    placeholder_text = Passwort
    halign = center
    valign = center
}
