preload = /home/withold/.config/hypr/wallpapers/artemis-wide.jpg
wallpaper = HDMI-A-1,/home/withold/.config/hypr/wallpapers/artemis-wide.jpg
wallpaper = eDP-1,/home/withold/.config/hypr/wallpapers/artemis-wide.jpg
